#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: num:nil toc:nil
#+BEGIN_EXPORT html
---
title:  Nahamcon CTF 2022
categories:
  - blog
tags:
    - CTF
---
#+END_EXPORT

So what a weekend, Tears sweat and a lot of Brainpower... the few houres I had to spend where amazing. Really Fun, asn definitly a challange, or some.

I learnt a ton of new stuff, and especially all the CFT related, things which where new to me.... I expected a lot more of Web hacking, and a little less of all the other stuff.

Generally this are my results:

Robiks
*709th place* (Not that bad for a One-Man show and ~3200 Teams
*918 points*

Solves
| Challenge         | Category | Value | Time                    |
|-------------------+----------+-------+-------------------------|
| Flagcat           | Warmups  |    50 | April 29th, 9:04:35 AM  |
| Technical Support | Warmups  |    50 | April 29th, 9:07:22 AM  |
| Read The Rules    | Warmups  |    50 | April 29th, 9:10:31 AM  |
| Exit Vim          | Warmups  |    50 | April 29th, 9:12:45 AM  |
| Prisoner          | Warmups  |    50 | April 29th, 2:19:11 PM  |
| Crash Override    | Warmups  |    50 | April 29th, 2:45:29 PM  |
| Quirky            | Warmups  |    50 | April 29th, 2:53:46 PM  |
| Jurassic Park     | Web      |    50 | April 29th, 2:59:33 PM  |
| Personnel         | Web      |    50 | April 29th, 3:34:11 PM  |
| EXtravagant       | Web      |    50 | April 29th, 3:41:21 PM  |
| Keeber 1          | OSINT    |    50 | April 29th, 5:13:12 PM  |
| Keeber 4          | OSINT    |   318 | April 30th, 10:23:42 AM |
| Keeber 5          | OSINT    |    50 | April 30th, 12:31:46 PM |

I still have to process the huge amounts of mistakes I made, and issues I had. Mostly with not really trusting my selve.
E.g. in the Gossip challange where I messed up the ssh key, and instead of focusing on that I tried everthing else. Which was obviously false.
Also with the Keeber challenge... I was thinking on the Wayback Url's But I was never looking at the Internet Archive... I need to stick to my ideas.. they are mostly not that wrong.

If I had more time I would also write a Write-up... but thats not possible at the moment.
But really I enjoyed it a lot. But the Reverse Engigneering Challange really bothers me a lot.

And I have some new topics to look at:
 - Binary Exploitation
 - Android Hacking
