#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: num:nil toc:nil
#+BEGIN_EXPORT html
---
title:  Everthing backwards
categories:
  - blog
tags:
    - CTF
    - RE
---
#+END_EXPORT

Honestly, I really enjoy the reverse-enginieering topics. Maybe because this taps into my knowlege from years ago.

But blocking reverse attempts be just a slight modification of the ELF Header, is honestly amazing.
https://pentester.blog/?p=247

Also the R2 tool is wonderful, although I honestly have not too much experience in how to use it properly.

But this lack of experince can only be filles with some fun CTFs, and honestly I really enjoyed the challanges from THM for the
reverse engineering. They were mostly fun, and not too hard, at least after I understood the basic usare of randare2

https://rada.re/n/radare2.html

This tool really amazes me, not only for the purpose, also how efficient the commandline interface is, and I've really seen my fair share of
debuggers. This one is definitly the coolest one.
