#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: num:nil toc:nil
#+BEGIN_EXPORT html
---
title:  Let's polute some Prototypes
categories:
  - blog
tags:
    - XSS
    - JS
---
#+END_EXPORT

So I spent some hours on the Intigrity challange, and while I was able to bypass the sanatization, and learnd quite some tricks, I was miles away from solving it.
And honestly reading the writups, I did not even know this is possible. Ao I still have quite a lot to learn on the JS side.

Following this write-up and the video, I'm finally able to understand what should be done.
https://github.com/goku-KaioKen/intigriti/blob/main/challenge-writeups/Challenge-0422.pdf

I think the most valueable lession is that I know now that prototype Polution exists :).
https://portswigger.net/daily-swig/prototype-pollution-the-dangerous-and-underrated-vulnerability-impacting-javascript-applications

This description gives some more insight on this.
but basically this small example shows everthing we need to know.

#+begin_src js :results output
let customer = {name: "person", address: "here"}
console.log(customer.toString())
//output: "[object Object]"

customer.__proto__.toString = ()=>{alert("polluted")}
console.log(customer.toString())
// alert box pops up: "polluted"
#+end_src

Besides this I did my first KOTH on THM, which was quite fun, but I was destroid by a kid halv my age :) Yes this shows me again how much I still need to learn.

But as THM not even shows an prototype pollution rooms, I understand that this integrity challanges are defenitly out of my league, but maybe thats the thin I need?
